### ISSUE TITLE
Things to-do

### ISSUE THREAD

**Issue by CGA1123** [carwow/umbra#1]
- [x] Document Configuration options
- [ ] Abstract away dependency on `redis`?
- [x] Full end-to-end test using some `app = proc { [200, {}, []] }`
- [x] Probably more docs 😛 
- [x] Configurable `logger`
- [x] add a `verify!` after `Umbra.configure` yields? (done for redis connection)
- [ ] Add ability to set tolerance to throttle shadowing (e.g exponential backoff when P99 > x ms)
